<!-- Contextual menu for selected messages -->
<div class="actions menu<?php echo isset( $sticky ) ? ' sticky' : ''; ?>">
<?php
if ( isset( $threadView ) ): ?>
    <a href="<?php echo App\Url::getRefUrl(); ?>" class="icon button control" data-tooltip="Back">
        <i class="fa fa-arrow-left"></i>
    </a>
<?php
else: ?>
    <div class="dropdown inline-blocked control">
        <a href="#" class="icon button" data-tooltip="Select">
            <i class="fa fa-minus-square-o"></i>
            <i class="fa fa-caret-down"></i>
        </a>
        <ul>
            <li>
                <input type="submit" name="select" value="All" />
            </li>
            <li>
                <input type="submit" name="select" value="None" />
            </li>
            <li>
                <input type="submit" name="select" value="Read" />
            </li>
            <li>
                <input type="submit" name="select" value="Unread" />
            </li>
            <li>
                <input type="submit" name="select" value="Starred" />
            </li>
            <li>
                <input type="submit" name="select" value="Unstarred" />
            </li>
        </ul>
    </div>
<?php
endif; ?>
    <button name="action" value="archive" class="icon button control" data-tooltip="Archive">
        <i class="fa fa-archive"></i>
    </button>
    <button name="action" value="delete" class="icon button control" data-tooltip="Delete">
        <i class="fa fa-trash-alt"></i>
    </button>
    <button name="action" value="mark_read" class="icon button control">
        <span class="normal">Mark as read</span>
    </button>
    <a href="#move-messages" class="icon button control" data-tooltip="Move to">
        <i class="far fa-folder"></i>
        <i class="fa fa-plus"></i>
    </a>
    <a href="#apply-labels" class="icon button control" data-tooltip="Labels">
        <i class="fa fa-tag"></i>
        <i class="fa fa-plus"></i>
    </a>
    <div class="dropdown inline-blocked control">
        <a href="#" class="icon button">
            <span class="normal">More</span>
            <i class="fa fa-caret-down"></i>
        </a>
        <ul class="more-actions">
            <li>
                <input type="submit" name="action" value="Mark as unread" />
            </li>
            <li>
                <input type="submit" name="action" value="Move to Inbox" />
            </li>
            <li>
                <input type="submit" name="action" value="Add star" />
            </li>
            <li>
                <input type="submit" name="action" value="Remove star" />
            </li>
        </ul>
    </div>
</div><!-- /actions menu -->