<section id="msg-actions" class="no-select">
    <!-- Default menu for unselected messages -->
    <div class="default menu">
        <div class="dropdown inline-blocked control">
            <a href="#" class="icon button" data-tooltip="Select" tabindex="-1">
                <i class="far fa-square"></i>
                <i class="fa fa-caret-down"></i>
            </a>
            <ul>
                <li>
                    <input type="submit" name="select" value="All" />
                </li>
                <li>
                    <input type="submit" name="select" value="None" />
                </li>
                <?php
                if (OUTBOX !== $folderLabel ?? null): ?>
                <li>
                    <input type="submit" name="select" value="Read" />
                </li>
                <li>
                    <input type="submit" name="select" value="Unread" />
                </li>
                <li>
                    <input type="submit" name="select" value="Starred" />
                </li>
                <li>
                    <input type="submit" name="select" value="Unstarred" />
                </li>
                <?php
                endif; ?>
            </ul>
        </div><!--
        --><button type="submit" name="refresh" value="1" class="icon button control" data-tooltip="Refresh" tabindex="4">
            <i class="fa fa-redo-alt"></i>
        </button><!--
        --><div class="dropdown inline-blocked control">
            <a href="#" class="icon button">
                <span class="normal">More</span>
                <i class="fa fa-caret-down"></i>
            </a>
            <ul>
                <?php
                if (! isset($folderLabel) || OUTBOX !== $folderLabel): ?>
                <li>
                    <input type="submit" name="action" value="Mark all as read" />
                </li>
                <li>
                    <input type="submit" name="action" value="Mark all as unread" />
                </li>
                <?php
                endif; ?>
                <li class="notice">
                    <em>
                        Select messages to see more actions
                    </em>
                </li>
            </ul>
        </div>
    </div>
</section>