<?php
if ((int) $folder->ignored !== 1 && ! $folder->is_mailbox): ?>
    <li class="<?php echo $folders->getNavClassString($folder->id, $activeId, $children); ?>">
        <input type="checkbox" id="folder-<?php echo $folder->id; ?>-checkbox" class="folder-checkbox" />
        <a href="<?php echo App\Url::folder($folder->id); ?>" class="mailbox">
            <?php $view->clean($folder->name); ?><?php echo $folder->unread_count ? ' ('. $folder->unread_count .')' : ''; ?>
        </a>
        <label for="folder-<?php echo $folder->id; ?>-checkbox" class="folder-label">
        <?php
        if ($children): ?>
            <i class="fa fa-caret-right"></i>
            <i class="fa fa-caret-down"></i>
        <?php
        endif; ?>
        </label>
        <a class="color color-<?php echo $folder->color->name; ?>"></a>
    <?php
    if ($children): ?>
        <ul class="sub">
        <?php
        foreach ($children as $child):
            $view->render('nav/folder', [
                'view' => $view,
                'folders' => $folders,
                'activeId' => $activeId,
                'folder' => $child['folder'],
                'children' => $child['children']
            ]);
        endforeach; ?>
        </ul>
    <?php
    endif; ?>
    </li>
<?php
endif; ?>
