<!-- Contextual menu for selected messages -->
<div class="actions menu">
    <div class="inline-blocked">
        <div class="dropdown inline-blocked control">
            <a href="#" class="icon button" data-tooltip="Select">
                <i class="far fa-minus-square"></i>
                <i class="fa fa-caret-down"></i>
            </a>
            <ul>
                <li>
                    <input type="submit" name="select" value="All" />
                </li>
                <li>
                    <input type="submit" name="select" value="None" />
                </li>
            </ul>
        </div>
    </div><!--
    --><div class="inline-blocked">
        <button name="action" value="restore_draft" class="icon button control">
            <span class="normal">Cancel delivery!</span>
        </button>
    </div>
</div><!-- /outbox actions menu -->
