<!-- Label sidebar -->
<div class="folder-selector" id="apply-labels">
    <h4 class="u-cf">
        <span>Apply Labels</span>
        <a href="#" class="close">
            <i class="fa fa-times"></i>
        </a>
    </h4>
    <input type="search" list="folder-list" value="" name="copy_to[]" placeholder="Search..." />
    <div class="list">
    <?php
    foreach ($folders as $folder): ?>
        <input type="checkbox" value="<?php $view->clean($folder->full_name ); ?>" name="copy_to[]"
            class="move-to-checkbox" id="label-checkbox-<?php echo $folder->id; ?>"
            <?php echo $folder->selected ? 'checked="checked"' : '' ?> />
        <label for="label-checkbox-<?php echo $folder->id; ?>">
            <?php $view->clean($folder->full_name); ?>
        </label>
    <?php
    endforeach; ?>
    </div>
    <div class="actions">
        <button type="submit" name="action" value="copy" class="icon button button-primary">
            <i class="fa fa-tag"></i>&nbsp;
            <span class="long-text">Apply Labels to Messages</span>
            <span class="short-text">Apply Labels</span>
        </button>
        <button type="submit" name="action" value="uncopy" class="icon button button-danger u-pull-right">
            <i class="fa fa-trash"></i>&nbsp;
            Remove Labels
        </button>
    </div>
</div><!-- /apply labels selector -->