<?php
foreach ( $messages as $message ): ?>
    <input type="checkbox" name="message[]" value="<?php echo $message->id; ?>"
        id="msg-checkbox-<?php echo $message->id; ?>" class="msg-checkbox" />
    <label for="msg-checkbox-<?php echo $message->id; ?>" class="msg-label"></label>
    <div class="msg-contents <?php echo $message->seen == 1 ? 'seen' : 'unseen'; ?>" id="msg-contents-<?php echo $message->id; ?>">
        <div class="star">
        <?php
        if ( $message->flagged == 1 ): ?>
            <i class="fa fa-star"></i>
        <?php
        else: ?>
            <i class="fa fa-star-o"></i>
        <?php
        endif; ?>
        </div>
        <div class="names">
            <?php echo $message->names; ?>
        </div>
        <a href="#" class="subject">
            <span><?php echo $message->subject; ?></span>&nbsp;<?php echo $message->snippet; ?>
        </a>
        <div class="date">
            <?php echo $message->display_date; ?>
        </div>
    </div>
    <div class="u-cf"></div>
<?php
endforeach; ?>