<input type="checkbox" id="<?php echo $id; ?>-checkbox" class="mailbox-checkbox" />
<h5>
    <label for="<?php echo $id; ?>-checkbox">
        <i class="fa fa-caret-down arrow"></i>
        <i class="fa fa-caret-right arrow"></i>
    </label>
    <span><?php echo $heading; ?></span>
    <a href="<?php echo App\Url::make( '/folder/%s', $folderId ); ?>">
        <strong><?php echo $counts->start; ?></strong>
        <var>&ndash;</var>
        <strong><?php echo $counts->end; ?></strong>
        <em>of</em>
        <strong><?php echo $counts->total; ?></strong>
    </a>
</h5>
<div id="<?php echo $id; ?>" class="mailbox">
    <?php
    $view->render( 'messages/messages', [
        'view' => $view,
        'select' => $select,
        'messages' => $messages
    ]);
    $view->render( 'messages/actions-menu' ); ?>
</div>