<input type="checkbox" id="<?php echo $id; ?>-checkbox" class="mailbox-checkbox" />
<h5>
<?php
if (! $showPaging): ?>
    <label for="<?php echo $id; ?>-checkbox">
        <i class="fa fa-caret-down arrow"></i>
        <i class="fa fa-caret-right arrow"></i>
    </label>
    <span><?php $view->clean($heading); ?></span>
<?php
else: ?>
    <?php $view->clean($heading); ?><?php if ($urlId === STARRED): ?>&nbsp;&mdash;&nbsp;Starred<?php endif; ?>
<?php
endif;
if ($showPaging): ?>
    <span class="paging-counts">
    <?php
    if ($counts->prevPage):
        if ($urlId === SEARCH):
            $url = App\Url::makeGet('/search', ['p' => $counts->prevPage]);
        else:
            $url = $urlId === STARRED
                ? App\Url::make('/starred/%s', $counts->prevPage)
                : App\Url::make('/folder/%s/%s', $folderId, $counts->prevPage);
        endif; ?>
        <a class="page prev" href="<?php echo $url; ?>"><i class="fa fa-chevron-left"></i>&nbsp;Prev</a>
    <?php
    endif;
    if ($counts->total): ?>
        <strong><?php echo $counts->start; ?></strong>
        <var>&ndash;</var>
        <strong><?php echo $counts->end; ?></strong>
        <em>of</em>
        <strong><?php echo $counts->total; ?></strong>
    <?php
    endif;
    if ($counts->nextPage):
        if ($urlId === SEARCH):
            $url = App\Url::makeGet('/search', ['p' => $counts->nextPage]);
        else:
            $url = $urlId === STARRED
                ? App\Url::make('/starred/%s', $counts->nextPage)
                : App\Url::make('/folder/%s/%s', $folderId, $counts->nextPage);
        endif; ?>
        <a class="page next" href="<?php echo $url; ?>">Next&nbsp;<i class="fa fa-chevron-right"></i></a>
    <?php
    endif; ?>
    </span>
<?php
elseif ($counts->total ?? 0):
    $url = $urlId === STARRED
        ? App\Url::make('/starred/%s', $counts->page)
        : App\Url::make('/folder/%s/%s', $folderId, $counts->page); ?>
    <a class="paging-counts" href="<?php echo $url; ?>">
        <strong><?php echo $counts->start; ?></strong>
        <var>&ndash;</var>
        <strong><?php echo $counts->end; ?></strong>
        <em>of</em>
        <strong><?php echo $counts->total; ?></strong>
    </a>
<?php
endif;
/* Unused right now
   Currently the search method returns IDs only, and we don't have
   the score information attached to the thread. It's simple but
   time-consuming to refactor.
   Uncommenting this will enable the sorting.
if ($urlId === SEARCH): ?>
    <span class="sort-controls">
        Sort:&nbsp;
        <a class="control<?php echo (App\Url::getParam('s') ?: 'date') === 'date' ? ' active' : ''; ?>"
            href="<?php echo App\Url::makeGet('/search', ['s' => 'date']); ?>">Date</a>,<!--
        --><a class="control<?php echo App\Url::getParam('s') === 'score' ? ' active' : ''; ?>"
            href="<?php echo App\Url::makeGet('/search', ['s' => 'score']); ?>">Relevancy</a>
    </span>
<?php
endif;
*/ ?>
</h5>
<div id="<?php echo $id; ?>" class="mailbox">
<?php
if ($messages):
    $view->render('messages/messages', [
        'view' => $view,
        'select' => $select,
        'isOutbox' => false,
        'folderId' => $folderId,
        'messages' => $messages,
        'isDrafts' => $folderId === $folders->getDraftsId()
    ]);
    $view->render('nav/actions-menu', [
        'folders' => $folders,
        'folderId' => $folderId
    ]);
else:
    $view->render('messages/no-messages');
endif; ?>
</div>
