<!-- Folder sidebar -->
<div class="folder-selector" id="move-messages">
    <h4 class="u-cf">
        <span>Move Messages</span>
        <a href="#" class="close">
            <i class="fa fa-times"></i>
        </a>
    </h4>
    <input type="search" list="folder-list" value="" name="move_to[]" placeholder="Search...">
    <div class="list">
    <?php
    foreach ( $folders as $folder ): ?>
        <input type="checkbox" value="<?php $view->clean( $folder->full_name ); ?>" name="move_to[]"
            class="move-to-checkbox" id="moveto-checkbox-<?php echo $folder->id; ?>">
        <label for="moveto-checkbox-<?php echo $folder->id; ?>">
            <?php $view->clean( $folder->full_name ); ?>
        </label>
    <?php
    endforeach; ?>
    </div>
    <div class="actions">
        <button type="submit" name="action" value="move" class="icon button button-secondary">
            <i class="far fa-folder-open"></i>&nbsp;
            Move to Selected Folders
        </button>
        <span class="hint">
            <i class="fa fa-arrow-left"></i>
            Save
        </span>
    </div>
</div><!-- /move messages selector -->
