<?php

/**
 * ================================================================
 * DO NOT EDIT THIS FILE
 *
 * This contains the system constants and should not be edited for
 * normal use. Please make any configuration edits in local.ini.
 * ================================================================
 */

// Application
define('APP_NAME', 'LibreMail');
define('APP_VERSION', '0.1.0');
define('BASEPATH', __DIR__.'/../');
define('DBSCRIPTS', __DIR__.'/db/*.sql');
define('ENDPOINT_WEB', '/');
define('ENDPOINT_STATS', '/stats');
define('JSON_HEADER_CHAR', '#');
define('DEFAULT_SERVICE', 'other');

// Models
define('META', 'meta');
define('TASK', 'task');
define('FOLDER', 'folder');
define('OUTBOX', 'outbox');
define('ACCOUNT', 'account');
define('MESSAGE', 'message');

// Dates
define('DATE_LOG', 'j-M-y H:i:s');
define('DATE_DATABASE', 'Y-m-d H:i:s');

// Executables
define('EXEC_SYNC', '/sync -b -d');
define('EXEC_SERVER', '/server -b -d');
define('PROC_SYNC', 'sync');
define('PROC_SERVER', 'server');

// Exceptions
define('EXC_FATAL', 1001);
define('EXC_ERROR', 1002);
define('EXC_TERM', 1003);
define('EXC_LOG_PATH', 1004);
define('EXC_ATTACH_PATH', 1005);
define('EXC_STOP', 1006);
define('EXC_RESTART', 1007);
define('EXC_VALIDATION', 2001);
define('EXC_DB_INSERT', 2002);
define('EXC_DB_UPDATE', 2003);
define('EXC_DB_NOTFOUND', 2004);
define('EXC_DB_MAX_PACKET', 2005);
define('EXC_ACCOUNT_EXISTS', 2010);
define('EXC_MESSAGES_SYNC', 3001);
define('EXC_FOLDER_SYNC', 3002);
define('EXC_BAD_COMMAND', 4001);

// Errors
define('ERR_DATABASE', 'database');

// Statuses
define('STATUS_SKIP', 'skip');
define('STATUS_ERROR', 'error');
define('STATUS_SUCCESS', 'success');
define('STATUS_WARNING', 'warning');

// Events
define('EV_STOP_SYNC', 'sync.stop');
define('EV_POLL_STATS', 'stats.poll');
define('EV_START_SYNC', 'sync.start');
define('EV_STOP_INBOX', 'inbox.stop');
define('EV_SYNC_EXITED', 'sync.exited');
define('EV_START_INBOX', 'inbox.start');
define('EV_POLL_DAEMON', 'daemon.poll');
define('EV_START_SERVER', 'server.start');
define('EV_SERVER_EXITED', 'server.exited');
define('EV_CONTINUE_SYNC', 'sync.continue');
define('EV_BROADCAST_MSG', 'daemon.broadcast');
