<div id="draft-alert" class="alert">
    <p>
        This draft is stored on the remote mailbox. To edit it here,
        <?php $view->clean($view->env('NAME', LIBREMAIL)); ?> will first
        create a copy, and then <strong>delete this version.</strong>
        This is safe and you can undo the operation or restore it from
        your trash.
    </p>
    <p>
        <button name="action" value="convert_draft" class="icon button button-secondary">
            <i class="far fa-edit"></i>&nbsp;
            Edit draft in <?php $view->clean($view->env('NAME', LIBREMAIL)); ?>
        </button>
    </p>
</div>
