<div class="thread-msg-row">
    <input id="thread-msg-checkbox-<?php echo $message->id; ?>" type="checkbox"
        class="thread-msg-checkbox"
        <?php echo $open === true ? ' checked' : '' ?>
        <?php echo $locked === true ? ' disabled' : ''?>>
    <label for="thread-msg-checkbox-<?php echo $message->id; ?>" class="thread-msg-label">
        <span class="snippet">
            <span class="avatar">
                <img src="<?php echo $message->avatar_url; ?>">
            </span><!--
            --><strong class="from"><?php $view->clean($message->from_name); ?></strong><!--
            --><span><?php $view->clean($message->snippet); ?></span>
        </span>
        <span class="date" title="<?php echo $message->datetime_string; ?>"><?php echo $message->date_string; ?></span>
        <iframe src="<?php echo App\Url::make( '/star/thread/%s/%s/%s.html', $view->meta(PREF_THEME, 'default'), $message->id, $message->flagged == 1 ? 'on' : 'off' ); ?>" class="star"></iframe>
    </label>
    <article id="message-<?php echo $message->id; ?>" class="thread-msg">
        <label for="thread-msg-checkbox-<?php echo $message->id; ?>" class="thread-msg-header u-cf">
            <span class="snippet">
                <span class="avatar">
                    <img src="<?php echo $message->avatar_url; ?>">
                </span>
                <span class="details blocked">
                    <span class="from blocked">
                        <strong><?php $view->clean($message->from_name); ?></strong>
                        <span><?php $view->clean($message->from_email); ?></span>
                    </span>
                    <span class="to blocked">
                        <span>to</span>
                        <span><?php echo $view->clean($message->to_names); ?></span>
                    </span>
                </span>
            </span>
            <span class="date" title="<?php echo $message->datetime_string; ?>"><?php echo $message->date_string; ?></span>
            <iframe src="<?php echo App\Url::make('/star/thread/%s/%s/%s.html', $view->meta(PREF_THEME, 'default'), $message->id, $message->flagged == 1 ? 'on' : 'off'); ?>" class="star"></iframe>
            <span class="actions">
                <span class="button-group">
                    <a href="#reply-all-<?php echo $message->id; ?>" class="button" title="Reply all">
                        <i class="fa fa-reply-all"></i>
                    </a><!--
                    --><span class="dropdown short inline-blocked">
                        <a href="#" class="button">
                            <i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="right-menu size-medium">
                            <li>
                                <i class="fa left-icon fa-reply"></i>
                                <a href="<?php echo App\Url::make('/reply/%s', $message->id); ?>">Reply</a>
                            </li>
                            <li>
                                <i class="fa left-icon fa-reply-all"></i>
                                <a href="<?php echo App\Url::make('/replyall/%s', $message->id); ?>">Reply all</a>
                            </li>
                            <li>
                                <i class="fa left-icon fa-share"></i>
                                <a href="<?php echo App\Url::make('/forward/%s', $message->id); ?>">Forward</a>
                            </li>
                            <li>
                                <i class="fa left-icon fa-external-link-alt"></i>
                                <a href="<?php echo App\Url::make('/original/%s', $message->id); ?>" target="_blank">Show original message</a>
                            </li>
                            <li>
                                <i class="fa left-icon fa-glasses"></i>
                                <a href="<?php echo App\Url::makeToken('/action', [
                                    'message' => [$message->id],
                                    'action' => App\Actions::MARK_UNREAD_FROM_HERE,
                                    'folder_id' => $folders->getInboxId()
                                ]); ?>">Mark unread from here</a>
                            </li>
                            <li>
                                <i class="fa left-icon fa-exclamation-triangle"></i>
                                <a href="<?php echo App\Url::makeToken('/action', [
                                    'message' => [$message->id],
                                    'action' => App\Actions::SPAM,
                                    'apply_to_all' => 0,
                                    'single_message' => 1,
                                    'folder_id' => $folders->getInboxId()
                                ]); ?>">Mark message as spam</a>
                            </li>
                            <li>
                                <i class="fa left-icon fa-trash-alt"></i>
                                <a href="<?php echo App\Url::makeToken('/action', [
                                    'message' => [$message->id],
                                    'action' => App\Actions::TRASH,
                                    'apply_to_all' => 0,
                                    'single_message' => 1,
                                    'folder_id' => $folders->getInboxId()
                                ]); ?>">Delete this message</a>
                            </li>
                        </ul>
                    </span>
                </span>
            </span>
        </label>
    <?php
    if ($outbox->exists()):
        if ($outbox->isDraft()): ?>
        <div class="draft-notice is-draft notifications">
            <div class="notification warning">
                This message is a draft, you can edit and send the message below.
            </div>
        </div>
        <?php
        elseif ($outbox->isScheduled()): ?>
        <div class="draft-notice notifications">
            <div class="notification info">
                This message is scheduled for delivery at <?php echo $message->getDeliveryDate(); ?>.
                <a href="<?php echo App\Url::preview($outbox->id); ?>">View outgoing message</a>.
            </div>
        </div>
        <?php
        endif;
    endif;
    if (! $outbox->exists() && ! $outbox->isDraft()): ?>
        <div class="message"><?php echo $message->body; ?></div>
    <?php
    endif; ?>
    </article>
    <?php
    if (true === ($last ?? false) || true === ($showReplyAll ?? false)):
        $view->render('threads/reply-form', [
            'view' => $view,
            'outbox' => $outbox,
            'account' => $account,
            'message' => $message,
            'visible' => true === ($showReplyAll ?? false),
            'addresses' => $outbox->exists() && $outbox->getAddresses()
                ? $outbox->getAddresses()
                : $message->getReplyAllAddresses(false, $account->email)
        ]);
    endif; ?>
</div>
