<div class="thread-msg-row">
    <input id="thread-msg-checkbox-<?php echo $message->id; ?>" type="checkbox"
        class="thread-msg-checkbox"
        <?php echo $open === true ? ' checked' : '' ?>
        <?php echo $locked === true ? ' disabled' : ''?> />
    <label for="thread-msg-checkbox-<?php echo $message->id; ?>" class="thread-msg-label">
        <span class="snippet">
            <span class="avatar">
                <img src="<?php echo $message->avatar_url; ?>" />
            </span><!--
            --><strong class="from"><?php $view->clean($message->from_name); ?></strong><!--
            --><span><?php $view->clean($message->snippet); ?></span>
        </span>
        <span class="date" title="<?php echo $message->datetime_string; ?>"><?php echo $message->date_string; ?></span>
        <iframe src="<?php echo App\Url::make( '/star/thread/%s/%s/%s.html', $view->meta(PREF_THEME, 'default'), $message->id, $message->flagged == 1 ? 'on' : 'off' ); ?>" class="star"></iframe>
    </label>
    <article id="message-<?php echo $message->id; ?>" class="thread-msg">
        <label for="thread-msg-checkbox-<?php echo $message->id; ?>" class="thread-msg-header u-cf">
            <span class="snippet">
                <span class="avatar">
                    <img src="<?php echo $message->avatar_url; ?>" />
                </span>
                <span class="details blocked">
                    <span class="from blocked">
                        <strong><?php $view->clean($message->from_name); ?></strong>
                        <span><?php $view->clean($message->from_email); ?></span>
                    </span>
                    <span class="to blocked">
                        <span>to</span>
                        <span><?php echo $view->clean($message->to_names); ?></span>
                    </span>
                </span>
            </span>
            <span class="date" title="<?php echo $message->datetime_string; ?>"><?php echo $message->date_string; ?></span>
            <iframe src="<?php echo App\Url::make('/star/thread/%s/%s/%s.html', $view->meta(PREF_THEME, 'default'), $message->id, $message->flagged == 1 ? 'on' : 'off'); ?>" class="star"></iframe>
            <span class="actions">
                <span class="button-group">
                    <a href="#reply-all-<?php echo $message->id; ?>" class="button" title="Reply all">
                        <i class="fa fa-reply-all"></i>
                    </a><!--
                    --><span class="dropdown short inline-blocked">
                        <a href="#" class="button">
                            <i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="right-menu size-medium">
                            <li>
                                <i class="fa left-icon fa-reply"></i>
                                <a href="<?php echo App\Url::make('/reply/%s', $message->id); ?>">Reply</a>
                            </li>
                            <li>
                                <i class="fa left-icon fa-reply-all"></i>
                                <a href="<?php echo App\Url::make('/replyall/%s', $message->id); ?>">Reply all</a>
                            </li>
                            <li>
                                <i class="fa left-icon fa-share"></i>
                                <a href="<?php echo App\Url::make('/forward/%s', $message->id); ?>">Forward</a>
                            </li>
                            <li>
                                <i class="fa left-icon fa-external-link-alt"></i>
                                <a href="<?php echo App\Url::make('/original/%s', $message->id); ?>" target="_blank">Show original message</a>
                            </li>
                            <li>
                                <i class="fa left-icon fa-glasses"></i>
                                <a href="<?php echo App\Url::makeToken('/action', [
                                    'message' => [$message->id],
                                    'action' => App\Actions::MARK_UNREAD_FROM_HERE,
                                    'folder_id' => $folders->getInboxId()
                                ]); ?>">Mark unread from here</a>
                            </li>
                            <li>
                                <i class="fa left-icon fa-exclamation-triangle"></i>
                                <a href="<?php echo App\Url::makeToken('/action', [
                                    'message' => [$message->id],
                                    'action' => App\Actions::SPAM,
                                    'apply_to_all' => 0,
                                    'single_message' => 1,
                                    'folder_id' => $folders->getInboxId()
                                ]); ?>">Mark message as spam</a>
                            </li>
                            <li>
                                <i class="fa left-icon fa-trash-alt"></i>
                                <a href="<?php echo App\Url::makeToken('/action', [
                                    'message' => [$message->id],
                                    'action' => App\Actions::TRASH,
                                    'apply_to_all' => 0,
                                    'single_message' => 1,
                                    'folder_id' => $folders->getInboxId()
                                ]); ?>">Delete this message</a>
                            </li>
                        </ul>
                    </span>
                </span>
            </span>
        </label>
        <div class="message"><?php echo $message->body; ?></div>
    </article>
    <?php
    if (isset($last) && true === $last): ?>
    <div id="reply-all-<?php echo $message->id; ?>" class="reply-all compose">
        <div class="row padded">
            <div class="one columns label">
                <label class="align-right">To:</label>
            </div>
            <div class="ten columns inherit">
                <span><!--
                <?php
                foreach ($message->getReplyAllAddresses(false, $account->email) as $address): ?>
                    --><span class="address" title="<?php $view->clean($address); ?>"><?php $view->clean($message->getName($address)); ?></span><!--
                <?php
                endforeach; ?>
                --></span>
            </div>
            <div class="one columns">
                <a href="<?php echo App\Url::make('/replyall/%s#edit', $message->id); ?>" class="align-right">Edit</a>
            </div>
        </div>
        <textarea name="reply_all[<?php echo $message->id; ?>]"></textarea>
        <div class="buttons">
            <button type="submit" name="send_draft[<?php echo $message->id; ?>]" class="button button-secondary">
                Save Draft
            </button>
            <button type="submit" name="send_preview[<?php echo $message->id; ?>]" class="button button-primary">
                Preview + Send
            </button>
            <span>or</span>
            <a href="#">Cancel</a>
        </div>
    </div>
    <div class="reply-controls">
        <a href="#reply-all-<?php echo $message->id; ?>" class="icon button control">
            <i class="fa fa-reply-all"></i>
            <span class="normal">Reply all</span>
        </a>
        <a href="<?php echo App\Url::make('/reply/%s', $message->id); ?>" class="icon button control">
            <i class="fa fa-reply"></i>
            <span class="normal">Reply</span>
        </a>
        <a href="<?php echo App\Url::make('/forward/%s', $message->id); ?>" class="icon button control">
            <i class="fa fa-share"></i>
            <span class="normal">Forward</span>
        </a>
    </div>
    <?php
    endif; ?>
</div>
