<h5 class="thread-title">
    <span class="strong"><?php $view->clean( $thread->getSubject() ); ?></span>
<?php
foreach ( $thread->getFolders() as $folder ): ?>
    <mark style="background-color:<?php echo $folder->color->bg; ?>; color:<?php echo $folder->color->fg; ?>"><?php $view->clean( $folder->label ); ?></mark>
    <?php
endforeach; ?>
</h5>
<article class="thread-msg">
    <div class="message">
        <?php echo nl2br( trim( $thread->message->text_plain ) ); ?>
    </div>
</article>
