<?php

$view->render('header', [
    'view' => $view,
    'pageTitle' => 'Compose Message',
]);

$view->render('nav', [
    'view' => $view,
    'activeId' => 0,
    'folders' => $folders
]); ?>

<section id="main" class="settings">
    <?php
    $view->render('notifications', [
        'messages' => $notifications
    ]); ?>

    <h5>Compose Message</h5>
    <div class="help-text">
        When you click Send, your message will be moved to the <code>Outbox</code>.
        Messages stay in the Outbox for 5-10 minutes before being sent. You can edit
        the message, schedule a specific time, or trash it before it gets sent.
    </div>
    <form action="/compose" method="post" class="compose">
        <div class="row addresses">
            <div class="two columns label">
                <label class="align-right" for="settings-email">To</label>
            </div>
            <div class="ten columns">
            <?php
            for ($i = 1; $i <= 10; $i++): ?>
                <input type="text" value="" list="contacts" required />
            <?php
            endfor; ?>
            </div>
        </div>
        <div class="row hidden addresses">
            <div class="two columns label">
                <label class="align-right" for="settings-email">CC</label>
            </div>
            <div class="ten columns">
                asdasd
            </div>
        </div>
        <div class="row hidden addresses">
            <div class="two columns label">
                <label class="align-right" for="settings-email">Bcc</label>
            </div>
            <div class="ten columns">
                asdasd
            </div>
        </div>
        <div class="row subject">
            <div class="two columns label">
                <label class="align-right" for="settings-email">Subject</label>
            </div>
            <div class="ten columns">
                <input type="text" name="subject" value="" required />
            </div>
        </div>
        <div class="row message">
            <div class="two columns label">
                <label class="align-right" for="settings-email">Message</label>
            </div>
            <div class="ten columns">
                <textarea></textarea>
            </div>
        </div>
        <div class="buttons">
            <div class="ten columns offset-by-two">
                <button type="submit" name="send_outbox" class="button button-primary" formnovalidate>
                    Send
                </button>
                <button type="submit" name="send_now" class="button button-secondary" formnovalidate>
                    Send Immediately
                </button>
                <span>or</span>
                <a href="/">Go back</a>
            </div>
        </div>
    </form>
</section>

<!-- Datalist for contacts -->
<datalist id="contacts">
<?php
foreach ($contacts as $contact): ?>
    <option value="<?php $view->clean($contact->name); ?>"><?php $view->clean($contact->name); ?></option>
<?php
endforeach; ?>
</datalist>

<?php
$view->render('footer', [
    'meta' => $meta
]); ?>