<?php

$view->render('header', [
    'view' => $view,
    'pageClass' => 'compose',
    'pageTitle' => 'Compose Message',
]);

$view->render('nav', [
    'view' => $view,
    'activeId' => 0,
    'folders' => $folders
]); ?>

<section id="main" class="compose">
    <?php
    $view->render('notifications', [
        'messages' => $notifications
    ]); ?>

    <h5>Compose Message</h5>
    <div class="help-text">
        When you click Send, your message will be moved to the <code>Outbox</code>.
        Messages stay in the Outbox for 5-10 minutes before being sent. You can edit
        the message, schedule a specific time, or trash it before it gets sent.
    </div>
    <form action="/compose" method="post">
        <div class="row addresses<?php echo isset($formErrors['to']) ? ' has-error' : ''; ?>">
            <div class="two columns label">
                <label class="align-right">To</label>
            </div>
            <div class="ten columns">
            <?php
            for ($i = 0; $i < 10; $i++): ?>
                <input type="text" name="to[]" list="contacts" required
                    value="<?php echo isset($formData['to'][$i]) ? $formData['to'][$i] : ''; ?>"
                    class="<?php echo isset($formErrors['to'][$i]) ? 'with-error' : ''; ?>" />
                <?php
                if (isset($formErrors['to'][$i])): ?>
                <div class="error-message"><?php echo $formErrors['to'][$i]; ?></div>
                <?php
                endif;
            endfor; ?>
            </div>
        </div>
        <input type="radio" id="toggle-cc" />
        <div class="row addresses <?php echo isset($formErrors['cc']) ? 'has-error' : 'hidden'; ?>">
            <div class="two columns label">
                <label class="align-right">Cc</label>
            </div>
            <div class="ten columns">
            <?php
            for ($i = 0; $i < 10; $i++): ?>
                <input type="text" name="cc[]" list="contacts" required
                    value="<?php echo isset($formData['cc'][$i]) ? $formData['cc'][$i] : ''; ?>" />
            <?php
            endfor; ?>
            </div>
        </div>
        <input type="radio" id="toggle-bcc" />
        <div class="row addresses <?php echo isset($formErrors['bcc']) ? 'has-error' : 'hidden'; ?>">
            <div class="two columns label">
                <label class="align-right" for="settings-email">Bcc</label>
            </div>
            <div class="ten columns">
            <?php
            for ($i = 0; $i < 10; $i++): ?>
                <input type="text" name="bcc[]" list="contacts" required
                    value="<?php echo isset($formData['bcc'][$i]) ? $formData['bcc'][$i] : ''; ?>" />
            <?php
            endfor; ?>
            </div>
        </div>
        <div class="row addresses from">
            <div class="two columns label">
                <label class="align-right">From</label>
            </div>
            <div class="ten columns">
                <span><?php $view->clean($account->fromAddress()); ?></span>
                <span class="show-hidden-addresses">
                <?php
                if (! isset($formErrors['cc'])): ?>
                    <label for="toggle-cc"><a>Cc</a></label>
                <?php
                endif;
                if (! isset($formErrors['bcc'])): ?>
                    <label for="toggle-bcc"><a>Bcc</a></label>
                <?php
                endif; ?>
                </span>
            </div>
        </div>
        <div class="row subject">
            <div class="two columns label">
                <label class="align-right" for="settings-email">Subject</label>
            </div>
            <div class="ten columns">
                <input type="text" name="subject" value="<?php echo $formData['subject'] ?? $message->subject; ?>" />
            </div>
        </div>
        <div class="row message">
            <div class="two columns label">
                <label class="align-right" for="settings-email">Message</label>
            </div>
            <div class="ten columns">
                <textarea name="text_plain"><?php echo $formData['text_plain'] ?? $message->text_plain; ?></textarea>
            </div>
        </div>
        <div class="buttons">
            <div class="ten columns offset-by-two">
            <?php
            if ($previewing): ?>
                <button type="submit" name="send_outbox" class="button button-primary" formnovalidate>
                    Looks good, send it!
                </button>
            <?php
            else: ?>
                <button type="submit" name="send_draft" class="button button-secondary" formnovalidate>
                    Save Draft
                </button>
                <button type="submit" name="send_preview" class="button button-primary" formnovalidate>
                    Preview + Send
                </button>
                <!--
                <button type="submit" name="send_now" class="button button-secondary" formnovalidate
                    <?php echo $view->env('COMPOSE_SEND_NOW') ? '' : 'disabled title="Not available"'; ?>>
                    Blind Send
                </button>
                -->
            <?php
            endif; ?>
                <span>or</span>
                <a href="/">Go back</a>
            </div>
        </div>
    </form>
</section>

<!-- Datalist for contacts -->
<datalist id="contacts">
<?php
foreach ($contacts as $contact): ?>
    <option value="<?php $view->clean($contact->name); ?>"><?php $view->clean($contact->name); ?></option>
<?php
endforeach; ?>
</datalist>

<?php
$view->render('footer', [
    'meta' => $meta
]); ?>