<?php

$view->render('header', [
    'view' => $view,
    'pageClass' => 'compose',
    'pageTitle' => 'Compose Message',
]);

$view->render('nav', [
    'view' => $view,
    'activeId' => 0,
    'folders' => $folders
]); ?>

<section id="main" class="compose">
    <?php
    $view->render('notifications', [
        'messages' => $notifications
    ]);

    if ($message->id): ?>
    <h5>
        <span>Edit Message</span>
        <a href="#confirm-delete">Delete this message</a>
    </h5>
    <?php
    else: ?>
    <h5>
        <span>Compose Message</span>
    </h5>
    <div class="help-text">
        Your message will remain a draft until you click <code>Preview + Send</code>.
        From there, you can send either send your message now, or schedule a specific
        delivery time.
    </div>
    <?php
    endif; ?>
    <form action="<?php echo App\Url::compose(); ?>" method="post">
        <div class="row input-row addresses<?php echo isset($formErrors['to']) ? ' has-error' : ''; ?>">
            <div class="two columns label">
                <label class="align-right">To</label>
            </div>
            <div class="ten columns">
            <?php
            for ($i = 0; $i < 10; $i++): ?>
                <input type="text" name="to[]" list="contacts" required
                    value="<?php $view->clean($formData['to'][$i] ?? ($message->to[$i] ?? '')); ?>"
                    class="<?php echo isset($formErrors['to'][$i]) ? 'with-error' : ''; ?>" />
                <?php
                if (isset($formErrors['to'][$i])): ?>
                <div class="error-message"><?php echo $formErrors['to'][$i]; ?></div>
                <?php
                endif;
            endfor; ?>
            </div>
        </div>
        <input type="radio" id="toggle-cc" />
        <div class="row input-row addresses <?php echo isset($formErrors['cc']) ? 'has-error' : 'hidden'; ?>">
            <div class="two columns label">
                <label class="align-right">Cc</label>
            </div>
            <div class="ten columns">
            <?php
            for ($i = 0; $i < 10; $i++): ?>
                <input type="text" name="cc[]" list="contacts" required
                    value="<?php $view->clean($formData['cc'][$i] ?? ($message->cc[$i] ?? '')); ?>"
                    class="<?php echo isset($formErrors['cc'][$i]) ? 'with-error' : ''; ?>" />
            <?php
            endfor; ?>
            </div>
        </div>
        <input type="radio" id="toggle-bcc" />
        <div class="row input-row addresses <?php echo isset($formErrors['bcc']) ? 'has-error' : 'hidden'; ?>">
            <div class="two columns label">
                <label class="align-right" for="settings-email">Bcc</label>
            </div>
            <div class="ten columns">
            <?php
            for ($i = 0; $i < 10; $i++): ?>
                <input type="text" name="bcc[]" list="contacts" required
                    value="<?php $view->clean($formData['bcc'][$i] ?? ($message->bcc[$i] ?? '')); ?>"
                    class="<?php echo isset($formErrors['bcc'][$i]) ? 'with-error' : ''; ?>" />
            <?php
            endfor; ?>
            </div>
        </div>
        <div class="row addresses from">
            <div class="two columns label">
                <label class="align-right">From</label>
            </div>
            <div class="ten columns">
                <span><?php $view->clean($account->fromAddress()); ?></span>
                <span class="show-hidden-addresses">
                <?php
                if (! isset($formErrors['cc'])): ?>
                    <label for="toggle-cc"><a href="#">Cc</a></label>
                <?php
                endif;
                if (! isset($formErrors['bcc'])): ?>
                    <label for="toggle-bcc"><a href="#">Bcc</a></label>
                <?php
                endif; ?>
                </span>
            </div>
        </div>
        <div class="row input-row subject">
            <div class="two columns label">
                <label class="align-right" for="settings-email">Subject</label>
            </div>
            <div class="ten columns">
                <input type="text" name="subject" value="<?php $view->clean($formData['subject'] ?? $message->subject); ?>" />
            </div>
        </div>
        <div class="row input-row message">
            <div class="two columns label">
                <label class="align-right" for="settings-email">Message</label>
            </div>
            <div class="ten columns">
                <textarea name="text_plain"><?php echo $formData['text_plain'] ?? $message->text_plain; ?></textarea>
                <div class="help-text align-right">
                    Markdown enabled
                </div>
            </div>
        </div>
        <div class="buttons">
            <div class="ten columns offset-by-two">
                <button type="submit" name="send_draft" class="button button-secondary" formnovalidate>
                    Save Draft
                </button>
                <button type="submit" name="send_preview" class="button button-primary" formnovalidate>
                    Preview + Send
                </button>
                <span>or</span>
                <a href="/">Go back</a>
                <input type="hidden" name="id" value="<?php echo $message->id ?? ''; ?>" />
            </div>
        </div>
    </form>
</section>

<!-- Datalist for contacts -->
<datalist id="contacts">
<?php
foreach ($contacts as $contact): ?>
    <option value="<?php $view->clean($contact->name); ?>"><?php $view->clean($contact->name); ?></option>
<?php
endforeach; ?>
</datalist>

<?php
$view->render('confirm', [
    'id' => 'confirm-delete',
    'confirmLabel' => 'Yes, delete it',
    'cancelLabel' => 'No!',
    'action' => App\Url::make('/outbox/delete'),
    'message' => 'Are you sure you want to delete this message?',
    'data' => [
        'id' => $message->id
    ]
]);

$view->render('footer', [
    'meta' => $meta,
    'alert' => $alert
]); ?>
