<div class="confirm dialog" id="<?php echo $id; ?>">
    <form method="<?php echo $method ?? 'POST'; ?>" action="<?php echo $action ?? ''; ?>">
        <div class="confirm-message"><?php echo $message; ?></div>
        <div class="dialog-controls">
            <a href="#" class="button button-danger"><?php echo $cancelLabel ?? 'Cancel'; ?></a>
            <button type="submit" class="button button-secondary" name="<?php echo $confirmName ?? 'submit'; ?>"<?php echo isset($confirmValue) ? ' value="'.$confirmValue.'"' : ''; ?>><?php echo $confirmLabel ?? 'Okay'; ?></button>
        </div>
        <?php
    if (isset($data)):
        foreach ($data as $key => $value): ?>
        <input type="hidden" name="<?php echo $key; ?>" value="<?php echo $value; ?>" />
        <?php
        endforeach;
    endif; ?>
    </form>
</div>
<div class="dialog-overlay"></div>
