<div class="confirm dialog" id="<?php echo $id; ?>">
    <form method="<?php echo $method ?? 'POST'; ?>" action="<?php echo $action ?? ''; ?>">
        <div class="confirm-message"><?php echo $message; ?></div>
        <div class="dialog-controls">
            <a href="#" class="button button-danger"><?php echo $cancelLabel ?? 'Cancel'; ?></a>
            <button type="submit" class="button button-secondary"><?php echo $confirmLabel ?? 'Okay'; ?></button>
        </div>
    </form>
</div>
<div class="dialog-overlay"></div>