<?php
if (isset($meta) && $meta): ?>
    <div class="top-layer u-cf">
        <div id="topnav-actions" class="dropdown u-pull-right">
            <div class="status u-pull-left">
                <div class="running">
                <?php
                if ((int) $meta->asleep === 1 || (int) $meta->running === 1): ?>
                    <i class="fa fa-wifi"></i>
                    <span>Online</span>
                <?php
                else: ?>
                    <i class="fa fa-power-off"></i>
                    <span><strong>Offline!</strong></span>
                <?php
                endif; ?>
                </div>
                <div class="asleep">
                <?php
                if ((int) $meta->asleep === 1 || (int) $meta->running !== 1): ?>
                    <i class="fa fa-moon"></i>
                    <span>Asleep</span>
                <?php
                else: ?>
                    <i class="fa fa-sync-alt"></i>
                    <span><strong>Syncing</strong></span>
                <?php
                endif; ?>
                </div>
            </div>
            <a class="icon button" href="#" tabindex="3">
                <i class="fa fa-sliders-h"></i>
            </a>
            <ul class="right-menu size-medium">
                <li>
                    <i class="fa left-icon fa-wrench"></i>
                    <a href="/settings">Settings &amp; Preferences</a>
                </li>
                <li>
                    <i class="fa left-icon fa-envelope"></i>
                    <a href="/account">Configure Email</a>
                </li>
            </ul>
        </div>
    </div>
<?php
elseif (isset($showSettingsMenu) && true === $showSettingsMenu): ?>
    <div class="top-layer u-cf">
        <div id="topnav-actions" class="dropdown u-pull-right">
            <a class="icon button" href="#" tabindex="3">
                <i class="fa fa-sliders-h"></i>
            </a>
            <ul class="right-menu size-medium">
                <li>
                    <i class="fa left-icon fa-wrench"></i>
                    <a href="/settings">Settings &amp; Preferences</a>
                </li>
                <li>
                    <i class="fa left-icon fa-envelope"></i>
                    <a href="/account">Configure Email</a>
                </li>
            </ul>
        </div>
    </div>
<?php
endif;

if (isset($alert) && $alert): ?>
    <div class="alerts">
        <input type="checkbox" id="alert-1" />
        <div class="alert">
            <span class="message"><?php echo $alert['message']; ?></span>
            <label for="alert-1">
                <i class="fa fa-times"></i>
            </label>
        <?php
        if ($alert['batch_id']): ?>
            <form method="post" action="<?php echo App\Url::make('/undo/%s', $alert['batch_id']); ?>">
                <input type="submit" value="Undo" />
            </form>
        <?php
        endif; ?>
        </div>
    </div>
<?php
endif; ?>
</body>
</html>