
    <div class="top-layer u-cf u-full-width">
        <div id="topnav-actions" class="dropdown u-pull-right">
            <a class="icon button" href="#" tabindex="2">
                <i class="fa fa-sliders-h"></i>
            </a>
            <ul class="right-menu size-medium">
                <li>
                    <i class="fa left-icon fa-wrench"></i>
                    <a href="#settings">Settings &amp; Preferences</a>
                </li>
                <li>
                    <i class="fa left-icon fa-envelope"></i>
                    <a href="#">Configure Email</a>
                </li>
            </ul>
        </div>
    </div>
</body>
</html>