<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>LibreMail<?php echo isset($pageTitle) ? ' &bull; '.$pageTitle : ''; ?></title>
    <meta name="author" content="">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/css/font-awesome.css" rel="stylesheet" type="text/css">
    <link href="/css/open-sans.css" rel="stylesheet" type="text/css">
    <link href="/css/normalize.css" rel="stylesheet" type="text/css">
    <link href="/css/skeleton.css" rel="stylesheet" type="text/css">
    <link href="/css/site.css" rel="stylesheet" type="text/css">
    <link href="/favicon.ico" rel="icon" type="image/png">
    <noscript>
        <style type="text/css">
            .js-display {
                display: none;
            }
        </style>
    </noscript>
</head>
<body class="theme-<?php echo App\Model\Meta::get(App\Model\Meta::THEME, 'default', $meta ?? null); ?>">
    <header class="u-cf">
        <h4 id="logo">
            <a href="/">LibreMail</a>
        </h4>
        <div id="search">
            <input type="search" value="" placeholder="Search..." tabindex="1" /><!--
            --><a class="icon button" href="#"><i class="fa fa-search"></i></a>
        </div>
        <div id="topnav">
            <!-- This is a top-layer action. A separate container will be
                fixed and positioned up here -->
        </div>
        <!--
        <aside class="js-display">
            <h6>You have JavaScript enabled!</h6>
            <div>You can and should disable it for this domain.</div>
        </aside>
        -->
    </header>