<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>LibreMail<?php echo isset($pageTitle) ? ' &bull; '.$pageTitle : ''; ?></title>
    <meta name="author" content="">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php
    if (false == $view->env('WEB_BUILD', true)): ?>
    <link href="/css/site.css" rel="stylesheet" type="text/css">
    <?php
    else: ?>
    <link href="/build/libremail.css" rel="stylesheet" type="text/css">
    <?php
    endif; ?>
    <link href="/favicon.ico" rel="icon" type="image/png">
    <noscript>
        <style type="text/css">
            .js-display {
                display: none;
            }
        </style>
    </noscript>
</head>
<body class="theme-<?php echo $view->meta(PREF_THEME, 'default'); ?> page-<?php echo $pageClass ?? 'main'; ?>">
    <header class="u-cf">
        <h4 id="logo">
            <a class="icon button" href="#" tabindex="3">
                <i class="fa fa-bars"></i>
            </a>
            <a href="/" class="link">LibreMail</a>
        </h4>
        <div id="search">
            <input type="search" value="" placeholder="Search..." tabindex="1" /><!--
            --><a class="icon button" href="#"><i class="fa fa-search"></i></a>
        </div>
        <div id="topnav">
            <!-- This is a top-layer action. A separate container will be
                fixed and positioned up here -->
        </div>
        <!--
        <aside class="js-display">
            <h6>You have JavaScript enabled!</h6>
            <div>You can and should disable it for this domain.</div>
        </aside>
        -->
    </header>