<?php
$view->render( 'header' );

$view->render( 'nav', [
    'view' => $view,
    'folderTree' => $folderTree
]); ?>

<section id="main">
    <form action="/update" method="post">
        <?php
        $view->render( 'messages/actions' ); ?>

        <section id="msg-list" class="no-select">
        <?php
        if ( $flagged ):
            $view->render( 'messages/message-list', [
                'view' => $view,
                'heading' => 'Starred',
                'messages' => $flagged,
                'id' => 'mailbox-starred',
                'counts' => $counts->flagged
            ]);
        endif;

            $view->render( 'messages/message-list', [
                'view' => $view,
                'messages' => $unflagged,
                'id' => 'mailbox-everything',
                'counts' => $counts->unflagged,
                'heading' => 'Everything else'
            ]);
            $view->render( 'messages/footer' ); ?>
        </section>

        <?php
        $view->render( 'messages/move-messages', [
            'folders' => $folders
        ]);
        $view->render( 'messages/apply-folder', [
            'folders' => $folders
        ]); ?>
    </form>
</section>

<?php
$view->render( 'messages/datalist', [
    'folders' => $folders
]);

$view->render( 'footer' ); ?>