<?php

$view->render('header');

$view->render('nav', [
    'view' => $view,
    'folders' => $folders,
    'activeId' => $folderId
]); ?>

<section id="main">
    <form action="/update" method="post">
        <?php
        $view->render('nav/actions'); ?>

        <section id="msg-list" class="no-select">
        <?php
        if ($flagged):
            $view->render('messages/message-list', [
                'view' => $view,
                'urlId' => STARRED,
                'select' => $select,
                'heading' => 'Starred',
                'messages' => $flagged,
                'folderId' => $folderId,
                'id' => 'mailbox-starred',
                'showPaging' => $showPaging,
                'counts' => $paging->flagged
            ]);
        endif;

            $view->render('messages/message-list', [
                'view' => $view,
                'urlId' => $urlId,
                'select' => $select,
                'folderId' => $folderId,
                'messages' => $unflagged,
                'heading' => $mainHeading,
                'showPaging' => $showPaging,
                'id' => 'mailbox-everything',
                'counts' => $paging->unflagged
            ]);

            $view->render('messages/footer', [
                'view' => $view,
                'meta' => $meta,
                'totals' => $totals
            ]); ?>
        </section>

        <?php
        $view->render('messages/move-messages', [
            'view' => $view,
            'folders' => $folders->getList()
        ]);
        $view->render('messages/apply-folder', [
            'view' => $view,
            'folders' => $folders->getList()
        ]); ?>

        <input type="hidden" name="page" value="<?php echo $page; ?>" />
        <input type="hidden" name="url_id" value="<?php echo $urlId; ?>" />
        <input type="hidden" name="folder_id" value="<?php echo $folderId; ?>" />
    </form>
</section>

<?php
$view->render('messages/datalist', [
    'view' => $view,
    'folders' => $folders->get()
]);

$view->render('footer', [
    'meta' => $meta
]); ?>