<nav class="no-select">
    <a id="compose" class="button button-primary" tabindex="3">Compose</a>
    <div id="nav-wrapper">
        <ul id="mailboxes">
        <?php
        if ( $folders->getInboxId() ): ?>
            <li class="<?php echo $activeId == $folders->getInboxId() ? 'active' : ''; ?>">
                <a href="/" class="mailbox">
                    Inbox<?php echo $folders->getUnreadCount( $folders->getInboxId(), TRUE ); ?>
                </a>
                <label class="folder-label"></label>
            </li>
        <?php
        endif;
        if ( $folders->getStarredId() ): ?>
            <li class="<?php echo $folders->getNavClassString( $folders->getStarredId(), $activeId ); ?>">
                <a href="<?php echo App\Url::folder( $folders->getStarredId() ); ?>" class="mailbox">
                    Starred<?php echo $folders->getUnreadCount( $folders->getStarredId(), TRUE ); ?>
                </a>
                <label class="folder-label"></label>
            </li>
        <?php
        endif;
        if ( $folders->getSentId() ): ?>
            <li class="<?php echo $folders->getNavClassString( $folders->getSentId(), $activeId ); ?>">
                <a href="<?php echo App\Url::folder( $folders->getSentId() ); ?>" class="mailbox">
                    Sent<?php echo $folders->getUnreadCount( $folders->getSentId(), TRUE ); ?>
                </a>
                <label class="folder-label"></label>
            </li>
        <?php
        endif;
        if ( $folders->getDraftsId() ): ?>
            <li class="<?php echo $folders->getNavClassString( $folders->getDraftsId(), $activeId ); ?>">
                <a href="<?php echo App\Url::folder( $folders->getDraftsId() ); ?>" class="mailbox">
                    Drafts<?php echo $folders->getUnreadCount( $folders->getDraftsId(), TRUE ); ?>
                </a>
                <label class="folder-label"></label>
            </li>
        <?php
        endif;
        if ( $folders->getAllId() ): ?>
            <li class="<?php echo $activeId == $folders->getAllId() ? 'active' : ''; ?>">
                <a href="<?php echo App\Url::folder( $folders->getAllId() ); ?>" class="mailbox">All Mail</a>
                <label class="folder-label"></label>
            </li>
        <?php
        endif; ?>
        </ul>
        <ul id="folders">
        <?php
        foreach ( $folders->getTree() as $item ):
            $view->render( 'nav/folder', [
                'view' => $view,
                'folders' => $folders,
                'activeId' => $activeId,
                'folder' => $item[ 'folder' ],
                'children' => $item[ 'children' ]
            ]);
        endforeach; ?>
        </ul>
    <?php
    if ( $folders->getSpamId() || $folders->getTrashId() ): ?>
        <div id="mailboxes-divider"></div>
        <ul id="mailboxes-more">
        <?php
        if ( $folders->getSpamId() ): ?>
            <li class="<?php echo $folders->getNavClassString( $folders->getSpamId(), $activeId ); ?>">
                <a href="<?php echo App\Url::folder( $folders->getSpamId() ); ?>" class="mailbox">
                    Spam<?php echo $folders->getUnreadCount( $folders->getSpamId(), TRUE ); ?>
                </a>
                <label class="folder-label"></label>
            </li>
        <?php
        endif;
        if ( $folders->getTrashId() ): ?>
            <li class="<?php echo $activeId == $folders->getTrashId() ? 'active' : ''; ?>">
                <a href="<?php echo App\Url::folder( $folders->getTrashId() ); ?>" class="mailbox">
                    Trash<?php echo $folders->getUnreadCount( $folders->getTrashId(), TRUE ); ?>
                </a>
                <label class="folder-label"></label>
            </li>
        <?php
        endif; ?>
        </ul>
    <?php
    endif; ?>
    </div>
</nav>