<?php

$view->render('header', [
    'view' => $view,
    'folders' => $folders
]);

$view->render('nav', [
    'view' => $view,
    'activeId' => 0,
    'folders' => $folders,
    'activeLabel' => OUTBOX
]); ?>

<section id="main">
    <form action="<?php echo App\Url::update(); ?>" method="post">
        <?php
        $view->render('nav/actions', [
            'folderLabel' => OUTBOX
        ]); ?>

        <section id="msg-list" class="no-select">
            <?php
            $view->render('notifications', [
                'messages' => $notifications
            ]); ?>
            <input type="checkbox" id="mailbox-outbox-checkbox" class="mailbox-checkbox">
            <h5>
                <span>Outbox</span>
            </h5>
            <div id="outbox" class="mailbox">
            <?php
            if ($messages):
                $view->render('messages/outbox-messages', [
                    'view' => $view,
                    'select' => $select,
                    'messages' => $messages,
                    'today' => $view::getDate(null, $view::DATE_FULL)
                ]);

                $view->render('nav/outbox-actions-menu');
            else:
                $view->render('messages/no-messages');
            endif; ?>
            </div>

            <?php
            $view->render('messages/footer', [
                'view' => $view,
                'meta' => $meta,
                'totals' => $totals
            ]); ?>

            <input type="hidden" name="url_id" value="<?php echo OUTBOX; ?>">
        </section>
    </form>
</section>

<?php
$view->render('footer', [
    'meta' => $meta,
    'alert' => $alert
]); ?>
