<?php

$view->render('header', [
    'view' => $view,
    'folders' => $folders,
    'pageClass' => 'compose',
    'pageTitle' => $message->isDraft()
        ? 'Preview and Send Message'
        : 'Outgoing Message'
]);

$view->render('nav', [
    'view' => $view,
    'activeId' => 0,
    'folders' => $folders
]); ?>

<section id="main" class="compose preview">
    <?php
    $view->render('notifications', [
        'messages' => $notifications
    ]);

    if ($message->isDraft()): ?>
    <h5>
        <span>Preview and Send Message</span>
        <a href="#confirm-delete">Delete this message</a>
    </h5>
    <?php
    else: ?>
    <h5 class="w-notification">
        <span>Outgoing Message</span>
    </h5>
    <div class="notifications">
        <div class="notification info">
            <div>This message is scheduled for delivery!</div>
            <div class="notification-actions">
                <a class="button button-secondary" href="#confirm-restore-draft">Cancel delivery</a>
            <?php
            if ($message->isPastDue()):
                if ((int) $meta->running === 1 || (int) $meta->asleep === 1): ?>
                <span>Sending shortly&hellip;</span>
                <?php
                else: ?>
                <span>Will be sent when sync starts (currently offline!)</span>
                <?php
                endif;
            else: ?>
                <span>
                    This message will be delivered:
                    <strong><?php echo $message->getDeliveryDate(); ?></strong>
                </span>
            <?php
            endif; ?>
            </div>
        </div>
    </div>
    <?php
    endif; ?>
    <form action="<?php echo App\Url::send(); ?>" method="post">
        <article class="outbox-preview">
            <!-- To -->
            <div class="row padded">
                <div class="two columns label">
                    <label class="align-right">To</label>
                </div>
                <div class="ten columns">
                <?php
                if ($message->to): ?>
                    <span><?php $view->clean(implode(',', $message->to)); ?></span>
                <?php
                else: ?>
                    <em class="error"><?php $view->clean($message->to ? implode(',', $message->to) : 'Missing'); ?></em>
                <?php
                endif; ?>
                </div>
            </div>
            <!-- From -->
            <div class="row padded">
                <div class="two columns label">
                    <label class="align-right">From</label>
                </div>
                <div class="ten columns">
                    <span><?php $view->clean($account->fromAddress()); ?></span>
                </div>
            </div>
            <!-- Subject -->
            <div class="row padded">
                <div class="two columns label">
                    <label class="align-right" for="settings-email">Subject</label>
                </div>
                <div class="ten columns">
                <?php
                if ($message->subject): ?>
                    <span><?php $view->clean($message->subject); ?></span>
                <?php
                else: ?>
                    <em class="error">No subject</em>
                <?php
                endif; ?>
                </div>
            </div>
            <div class="row padded message markdown">
                <div class="two columns label">
                    <label class="align-right" for="settings-email">Message</label>
                </div>
                <div class="ten columns text-html">
                <?php
                if ($message->text_html):
                    echo $message->text_html;
                else: ?>
                    <em class="error">No message body</em>
                <?php
                endif; ?>
                </div>
            </div>
        </article>
        <?php
        if ($message->isDraft()): ?>
        <div class="buttons">
            <button type="submit" name="edit" class="button button-secondary">
                Back to edit
            </button>
            <button type="submit" name="send_outbox" class="button button-success"<?php echo $message->to ? '' : ' disabled'; ?>>
                Send Message!
            </button>
            <!--
            <span id="schedule">
                <label class="inline-blocked">Send on:</label>
                <input type="datetime-local" name="send_after" value="" placeholder="">
            </span>
            <a href="#schedule" class="button button-primary"<?php echo $message->to ? '' : ' disabled'; ?>>
                Scheduled send
            </a>
            <button type="submit" name="send_outbox" class="button button-danger u-pull-right">
                Send now!
            </button>
            <button type="submit" name="send_now" class="button button-secondary" formnovalidate
                <?php echo $view->env('COMPOSE_SEND_NOW') ? '' : 'disabled title="Not available"'; ?>>
                Blind Send
            </button>
            -->
            <input type="hidden" name="id" value="<?php echo $message->id; ?>" />
        </div>
        <div class="help-text">
            When you click <code>Send</code>, your message will be moved to the Outbox.
            Messages stay in the Outbox for at least 1 minute before being sent.
            You can still edit the message, schedule a specific time, or trash it before
            it gets sent.
        </div>
        <?php
        endif; ?>
    </form>
</section>

<?php
$view->render('confirm', [
    'id' => 'confirm-delete',
    'confirmLabel' => 'Yes, delete it',
    'cancelLabel' => 'No!',
    'action' => App\Url::deleteOutbox(),
    'message' => 'Are you sure you want to delete this message?',
    'data' => [
        'id' => $message->id
    ]
]);

$view->render('confirm', [
    'id' => 'confirm-restore-draft',
    'confirmName' => 'action',
    'confirmValue' => 'restore_draft',
    'confirmLabel' => 'Yes, cancel delivery',
    'cancelLabel' => 'No!',
    'action' => App\Url::update(),
    'message' => 'Are you sure you want to cancel the delivery of this message?'
        .'<br><br>This will restore the message back to a draft, where you can edit it again.',
    'data' => [
        'message[]' => $message->id
    ]
]);

$view->render('footer', [
    'meta' => $meta,
    'alert' => $alert
]); ?>
