<?php

$view->render('header-light', [
    'view' => $view,
    'title' => 'Configure '.$view->env('NAME', LIBREMAIL).' Account'
]); ?>

<section id="main" class="settings setup">
    <?php
    $view->render('notifications', [
        'messages' => $notifications
    ]); ?>

    <h5>Configure Email Account</h5>
    <div class="help-text">
        Set your account email address, password, and the IMAP connection settings.
        Once you save your email address you cannot edit it here! Common settings for
        GMail are <code>imap.google.com</code> for the host, and port <code>993</code>.
    </div>
    <form action="/account/create" method="post">
        <div class="row">
            <div class="three columns label">
                <label class="align-right" for="settings-email">Email</label>
            </div>
            <div class="seven columns input">
                <input type="email" id="settings-email" name="email" value="<?php $view->clean($account->email ?: ''); ?>" placeholder="you@mail.com" required>
            </div>
        </div>
        <div class="row">
            <div class="three columns label">
                <label class="align-right" for="settings-password">Password</label>
            </div>
            <div class="seven columns input">
                <input type="password" id="settings-password" name="password" value="<?php $view->clean($account->password ?: ''); ?>" required>
                <div class="note align-right">
                    It's wise to
                    <a href="https://security.google.com/settings/security/apppasswords" target="_blank" title="Opens a new tab">use a token</a>
                    here!
                </div>
            </div>
        </div>
        <div class="row">
            <div class="three columns label">
                <label class="align-right" for="settings-name">Name</label>
            </div>
            <div class="seven columns input">
                <input type="text" id="settings-name" name="name" value="<?php $view->clean($account->name ?: ''); ?>" placeholder="Your Name" required>
            </div>
        </div>
        <div class="row">
            <div class="three columns label">
                <label class="align-right" for="settings-host">IMAP Address</label>
            </div>
            <div class="seven columns input">
                <input type="text" id="settings-host" name="host" value="<?php $view->clean($account->imap_host ?: ''); ?>" placeholder="imap.gmail.com">
            </div>
        </div>
        <div class="row">
            <div class="three columns label">
                <label class="align-right" for="settings-host">IMAP Port</label>
            </div>
            <div class="three columns input">
                <input type="text" id="settings-port" name="port" value="<?php $view->clean($account->imap_port ?: ''); ?>" placeholder="993">
            </div>
        </div>
        <div class="buttons row">
            <div class="seven columns offset-by-three input">
                <button type="submit" class="button button-secondary">
                    Save Account
                </button>
            </div>
        </div>
    </form>
</section>

<?php
$view->render('footer'); ?>
