<?php
$yellow = $theme === 'coolnight'
     ? '#a98304'
     : '#d6a70e'; ?>
<style type="text/css" nonce="<?php echo App\View::getNonce(); ?>">
    html {
        overflow: hidden;
    }
    body {
        margin: 0;
        padding: 0;
    }
    form {
        margin: 0;
    }
    div {
        box-sizing: border-box;
        height: 1.25rem;
    <?php
    if ($type === 'mailbox'): ?>
        margin-top: calc(50% - 0.625rem);
        padding-right: 0.2rem;
        text-align: center;
    <?php
    else: ?>
        margin-top: calc(50% - 0.3125rem);
        text-align: right;
    <?php
    endif; ?>
        width: 100%;
    }
    svg {
        cursor: hand;
        width: 1.25rem;
        height: 1.25rem;
    }
    button {
        border: none;
        background: none;
        padding: 0;
        outline: none;
    }
</style>
<div class="star-form">
    <form action="/star" method="post">
        <button type="submit">
            <!--
            xmlns="http://www.w3.org/2000/svg"
            xmlns:xlink="http://www.w3.org/1999/xlink"
            -->
            <svg version="1.1" x="0" y="0" viewBox="0, 0, 64, 64">
                <g>
                <?php
                if ( $flagged ): ?>
                    <path d="M13.938,61.064 L17.483,40.395 L2.466,25.757 L23.219,22.741 L32.5,3.936 L41.781,22.741 L62.534,25.757 L47.517,40.395 L51.062,61.064 L32.5,51.306 z" fill="<?php echo $yellow; ?>"/>
                    <path d="M13.938,61.064 L17.483,40.395 L2.466,25.757 L23.219,22.741 L32.5,3.936 L41.781,22.741 L62.534,25.757 L47.517,40.395 L51.062,61.064 L32.5,51.306 z" fill-opacity="0" stroke="<?php echo $yellow; ?>" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
                <?php
                else: ?>
                    <path d="M13.938,61.064 L17.483,40.395 L2.466,25.757 L23.219,22.741 L32.5,3.936 L41.781,22.741 L62.534,25.757 L47.517,40.395 L51.062,61.064 L32.5,51.306 z" fill="transparent"/>
                    <path d="M13.938,61.064 L17.483,40.395 L2.466,25.757 L23.219,22.741 L32.5,3.936 L41.781,22.741 L62.534,25.757 L47.517,40.395 L51.062,61.064 L32.5,51.306 z" fill-opacity="0" stroke="<?php echo $yellow; ?>" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
                <?php
                endif; ?>
                </g>
            </svg>
        </button>
        <input type="hidden" name="id" value="<?php echo $id; ?>" />
        <input type="hidden" name="type" value="<?php echo $type; ?>" />
        <input type="hidden" name="theme" value="<?php echo $theme; ?>" />
        <input type="hidden" name="state" value="<?php echo $flagged ? 'off' : 'on'; ?>" />
    </form>
</div>
