<?php

$view->render('header', [
    'view' => $view,
    'folders' => $folders
]);

$view->render('nav', [
    'view' => $view,
    'folders' => $folders,
    'activeId' => $folderId
]); ?>

<section id="main">
    <form action="<?php echo App\Url::update(); ?>" method="post">
        <div id="msg-actions">
            <?php
            $view->render('nav/actions-menu', [
                'sticky' => true,
                'thread' => $thread,
                'threadView' => true,
                'folders' => $folders,
                'folderId' => $folderId
            ]); ?>
        </div>

        <section id="msg-list">
            <?php
            if ($folders->getDraftsId() === $folderId && ! $thread->isOutboxMessage()):
                $view->render('threads/draft-alert', [
                    'view' => $view,
                    'thread' => $thread
                ]);
            endif;

            $view->render('threads/message-list', [
                'i' => 0,
                'view' => $view,
                'thread' => $thread,
                'account' => $account,
                'folders' => $folders
            ]);

            $view->render('messages/footer', [
                'view' => $view,
                'meta' => $meta,
                'totals' => $totals
            ]); ?>
        </section>

        <?php
        $view->render('messages/move-messages', [
            'view' => $view,
            'folders' => $folders->getList()
        ]);
        $view->render('messages/apply-folder', [
            'view' => $view,
            'folders' => $folders->getList($thread->getFolderIds())
        ]); ?>

        <input type="hidden" name="url_id" value="thread" />
        <input type="hidden" name="apply_to_all" value="1" />
        <input type="hidden" name="folder_id" value="<?php echo $folderId; ?>" />
        <input type="hidden" name="page" value="<?php echo $thread->getThreadId(); ?>" />
        <input type="hidden" name="message[]" value="<?php echo $thread->getThreadId(); ?>" />
    <?php
    foreach ($thread->getMessageIds() as $messageId): ?>
        <input type="hidden" name="message_all[]" value="<?php echo $messageId; ?>" />
    <?php
    endforeach; ?>
    </form>
</section>

<?php
$view->render('messages/datalist', [
    'view' => $view,
    'folders' => $folders->get(true)
]);

$view->render('footer', [
    'meta' => $meta,
    'alert' => $alert
]); ?>
